spring.application.name=barberia

#Configuración de la Base de Datos
spring.datasource.url=jdbc:mysql://localhost:3306/db_barberia
spring.datasource.username=barberspring
spring.datasource.password=BARBERIA2025

#Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#Para renderizar vistas HTML y hacer que Spring encuentre más rapido las plantillar
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html